# Generated by Django 5.2.1 on 2025-06-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='umbral_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
