# Generated by Django 5.2.1 on 2025-06-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default=1, max_length=10, verbose_name='Identificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(default=1, max_length=30, verbose_name='Nombre Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=1, max_length=10, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
