# Generated by Django 5.2.1 on 2025-06-08 23:46

from django.db import migrations
from django.contrib.auth import get_user_model

def crear_superusuario(apps, schema_editor):
    User = get_user_model()

    correo = "admin@admin.com"
    nombre = "Administrador General"
    password = "1234" 

    if not User.objects.filter(correo=correo).exists():
        User.objects.create_superuser(
            correo=correo,
            nombre_completo=nombre,
            password=password,
            is_active=True,
            es_admin=True,
            is_superuser=True,
        )
        print("Superusuario creado")
    else:
        print("El superusuario ya existe, no se creó uno nuevo")

class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_rename_activo_usuario_is_active'),
    ]

    operations = [
        migrations.RunPython(crear_superusuario),
    ]
