# Generated by Django 5.2.1 on 2025-06-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articulos', '0002_articulo_umbral_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('cantidad_total', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Articulos.articulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalidaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_cliente', models.BigIntegerField()),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='Movimientos.movimientoinventario')),
            ],
        ),
    ]
