# Generated by Django 5.2.1 on 2025-05-26 21:37

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('archivo', models.FileField(max_length=400, upload_to=Base.models.guardar_archivo, verbose_name='Archivo')),
                ('ruta_archivo', models.TextField(blank=True, default=None, null=True, verbose_name='Ruta del archivo')),
                ('nombre_archivo', models.TextField(verbose_name='Nombre del archivo')),
                ('url_archivo', models.TextField(blank=True, default=None, null=True, verbose_name='Url del archivo')),
                ('id_archivo', models.TextField(blank=True, default=None, null=True, verbose_name='ID del archivo')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivos',
            },
        ),
    ]
